
      gsap.from(".card1", { y:200,  duration: 1.2, opacity: 0})
      gsap.from(".card2", { y:-200, duration: 2, opacity: 0, delay: 1 })
      gsap.from(".card3", { y:200, duration: 2, opacity: 0, delay: 2 })
      gsap.from(".card4", { y:-200, duration: 2, opacity: 0, delay: 3 })
      gsap.from(".card5", { x:-200, duration: 2, opacity: 0, delay: 1 })
      gsap.from(".card6", { x:-200, duration: 2, opacity: 0, delay: 2 })
      gsap.from(".card7", { x:200, duration: 2, opacity: 0, delay: 3 })
      gsap.from(".card8", { x:-200, duration: 2, opacity: 0, delay: 4 })
      gsap.from(".title", { x:-200, duration: 2, opacity: 0, delay: 4 })